language: php

matrix:
  include:
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - php: 5.3
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source

script:
  - make lint
  - make test